topcoder-platform/member-api

- src/services/MemberService.js
> Decode email verify url to respect placeholder characters <>

- .circleci/config.yml
- config/default.js
- src/services/MemberTraitService.js
new trait onboarding_checklist
> added new trait onboarding_checklist

- config/default.js
Testing a new index to help fix: https://topcoder.atlassian.net/browse/PROD-2928
> Update the index used for searching to the new, more complex one.

- app-constants.js
- src/common/helper.js
- src/routes.js
- src/services/SearchService.js
Remove first name / last name from autocomplete
> Justin fixes

- app-constants.js
- src/common/helper.js
- src/services/SearchService.js
- restrict to users with roles: admin, administrator & tgadmin
> fix: restrict search by email

- .circleci/config.yml
- app-constants.js
- src/common/eshelper.js
- src/common/helper.js
- src/services/SearchService.js
* feat: query by email
* Added tgadmin to constants
* UnauthorizedError for No Token on query via Email
> feat: query by email (#105)

- config/default.js
- src/common/LookerApi.js
- src/common/LookerAuth.js
As per https://topcoder.atlassian.net/browse/MP-114
> MP-114 Looker API access support -> Justin's branch

- .circleci/config.yml
- config/default.js
- src/routes.js
- src/services/MemberTraitService.js
https://topcoder.atlassian.net/browse/MP-91
https://topcoder.atlassian.net/browse/MP-116
> Member profiles -> dev

- .circleci/config.yml
- config/default.js
- src/common/helper.js
https://topcoder.atlassian.net/browse/PROD-4307
API fixes related S3 uploads of member media.
> PROD-4307 -> dev

- src/common/helper.js
- src/services/MemberService.js
- src/services/SearchService.js
Final fix for public addresses.
Verified by me and @jmgasper
> Public city info -> dev

- src/services/SearchService.js
https://topcoder.atlassian.net/browse/MP-325
> Add availableForGigs and namesAndHandleAppearance to search results

- src/services/SearchService.js
@testflyjets - Per feedback:
https://github.com/topcoder-platform/member-api/pull/133#discussion_r1293613112
> Refactor additional data generation into individual functions

- src/services/SearchService.js
https://topcoder.atlassian.net/browse/TAL-67
> Support AND for multiple skills search, instead of OR

- src/common/eshelper.js
- src/services/SearchService.js
Reported in Slack:
https://topcoder.slack.com/archives/C02M1U90LC8/p1692724592604299
> PROD HOTFIX - fix problem with member search when limiting fields

- config/default.js
- src/controllers/MemberController.js
- src/routes.js
- src/services/MemberService.js
> PROD-4396 - add new endpoint to hash user's userId

- src/controllers/HealthController.js
- src/services/MemberService.js
https://topcoder.atlassian.net/browse/TSJR-270
Also updated the health check endpoint to be less resource intensive
> Remove skills from Joi data model so skills can’t be updated via member API

- src/services/SearchService.js
> Remove additional traits processing from skill score due to performance in prod

- src/services/SearchService.js
HOTFIX
Roll back skill score calculation updates while we refactor the data to be more performant
> HOTFIX - Roll back skill score calculation updates while we refactor the data to be more performant

- src/common/eshelper.js
- src/services/SearchService.js
As noted during QA, in the refactoring to avoid traits, I made a mistake in avatar and available for gigs checking.
> Calculation fix

- src/services/SearchService.js
Additional tweak for comparison test
> Testing fix

- src/common/eshelper.js
- src/services/MemberTraitService.js
- src/services/SearchService.js
> Use ES directly, instead of a bus event, for skill score deduction updates

- src/common/helper.js
- src/services/MemberService.js
- src/services/MemberTraitService.js
Only update the skill score if it's different, which avoids updating that field too often
> Data sync fixes

- src/common/helper.js
- src/services/StatisticsService.js
Prod crashing due to deprecated tags usage.  This PR removes the call to `getAllTags` from the codebase.
> HOTFIX - CORE-311

- .circleci/config.yml
- config/default.js
- docker/Dockerfile
- package.json
- src/common/eshelper.js
- src/common/helper.js
- src/scripts/migrate-names-and-gigs-traits.js
- src/scripts/migrate-traits.js
- src/scripts/view-es-data.js
- src/services/MemberService.js
- src/services/MemberTraitService.js
- yarn.lock
https://topcoder.atlassian.net/browse/PS-207
> PROD - Fix for handling of null values in addresses

- package-lock.json
- src/common/eshelper.js
https://topcoder.atlassian.net/browse/LVT-275
> LVT-275 : Fix for not seeing all autocomplete results

- src/init-es.js
- src/scripts/seed-data.js
- src/services/MemberService.js
- src/services/MemberTraitService.js
- test/testHelper.js
Fix broken services and rename .ES to .OS index config.
> .ES to .OS renaming

- src/init-es.js
- src/scripts/seed-data.js
- src/services/MemberService.js
- src/services/MemberTraitService.js
- test/testHelper.js
Reverts topcoder-platform/member-api#193
> Revert ".ES to .OS renaming"

- src/services/MemberService.js
https://topcoder.atlassian.net/browse/PM-325
> fix file-type-checker config

- .circleci/config.yml
- package-lock.json
- package.json
- src/common/image.js
- src/services/MemberService.js
- Fixed stored XSS vulnerability in upload photo functionality
Ticket link - https://topcoder.atlassian.net/browse/PM-1036
> fix(PM-1036): Stored XSS vulnerability

- .circleci/config.yml
- src/common/eshelper.js
- src/services/SearchService.js
Reverts topcoder-platform/member-api#204
> Revert "[PROD] - Talent search - unresponsive UI fix"

- .circleci/config.yml
- src/common/eshelper.js
- src/services/SearchService.js
Reverts topcoder-platform/member-api#203
> Revert "fix(PM-1448): Pagination in talent search"
